apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: strimzi-kafka-operator
  namespace: flux-system
spec:
  releaseName: strimzi-kafka-operator
  chart:
    spec:
      chart: strimzi-kafka-operator
      sourceRef:
        kind: HelmRepository
        name: cliffordt3-github
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  targetNamespace: kafka
  values:
    watchAnyNamespace: true
  