apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  releaseName: ig
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system 
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  targetNamespace: ingress
  values:
    # to support local access to ports
    controller:
      hostPort:      
        enabled: true
      admissionWebhooks:
        enabled: false  